// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week_3_Inno_PreTrainee.Data.Context;

#nullable disable

namespace Week_3_Inno_PreTrainee.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251028205515_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Week_3_Inno_PreTrainee.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1799, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Александр Пушкин"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Фёдор Достоевский"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Лев Толстой"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1860, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Антон Чехов"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1809, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Николай Гоголь"
                        });
                });

            modelBuilder.Entity("Week_3_Inno_PreTrainee.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = new DateTime(1833, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            PublishedYear = new DateTime(1866, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            PublishedYear = new DateTime(1869, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            PublishedYear = new DateTime(1904, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Вишнёвый сад"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            PublishedYear = new DateTime(1842, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Мёртвые души"
                        });
                });

            modelBuilder.Entity("Week_3_Inno_PreTrainee.Domain.Models.Book", b =>
                {
                    b.HasOne("Week_3_Inno_PreTrainee.Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Week_3_Inno_PreTrainee.Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
